---
  - name: Set up default encoding to utf8
    sudo: yes
    command: locale-gen en_US.UTF-8

  - name: Update locale for postgres
    sudo: yes
    command: update-locale LANG=en_US.UTF-8

  - name: Install PostgreSQL
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

  - name: Stop pgcluster
    sudo: yes
    command: pg_dropcluster --stop 9.1 main

  - name: Restart pgcluster
    sudo: yes
    command: pg_createcluster --start --locale en_US.UTF-8 9.1 main

  - name: ensure database is created
    sudo: yes
    sudo_user: postgres
    postgresql_db: name=vagrant

  - name: ensure user has access to database
    sudo: yes
    sudo_user: postgres
    postgresql_user: name=vagrant password=vagrant role_attr_flags=CREATEDB,NOSUPERUSER
